# -*- coding: utf-8 -*-
"""Addition of two images using openCV.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y1blDaw84QrLqkNZf6aYAv2uFJFDwSiU
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

earth = cv2.imread("/content/earth.jpg")

earth_rgb = cv2.cvtColor(earth,cv2.COLOR_BGR2RGB)
plt.imshow(earth_rgb);

Satellite = cv2.imread("/content/Satellite.png")

Satellite_rgb = cv2.cvtColor(Satellite,cv2.COLOR_BGR2RGB)
plt.imshow(Satellite_rgb);

print(f"The shape of image 1 and image 2 is {earth.shape} and {Satellite.shape} respectively")

earth = np.resize(earth,Satellite.shape)

added_images = cv2.add(earth,Satellite)

plt.imshow(added_images);